### ISSUE TITLE
load Bowerfile from installed Gems

### ISSUE THREAD

**Issue by fredericgrati** [rharriso/bower-rails#133]
I work on large scale rails application using a core gem. (to avoid duplication)
I would like to know if it is completely senseless to expect to use Bowerfile as rails application use Gemfile?

For example, don't have the Bowerfile at the root of my project but have multiple Bowerfile from installed gems.

**Comment by siassaj** [comment]
I'm having a similar problem with my isolated engine. In fact bundler ignores the Gemfile of my engine and instead uses the gemspec to understand the dependencies of my engine, and in fact all the other included gems.

So we must replicate that behaviour if this is to work properly, to collate all the bower dependencies from all the included gems, work out the versioning and then install them all. Would have been nice if they would be installed somewhere like ~/.bower_componensts similar to the ~/.gems directory.

I have to make this work in any case, so I'll review how bundler works and fork this, see what I can do.

**Comment by SergeyKishenin** [comment]
Check out #162
