### ISSUE TITLE
How can I install only 1 newly added package.

### ISSUE THREAD

**Issue by vuhailuyen1991** [rharriso/bower-rails#141]
How can I install only 1 newly added package without having to remove all packages and install everything over?

**Comment by SergeyKishenin** [comment]
What if you pass package name as and argument to a rake task https://github.com/rharriso/bower-rails#rake-tasks?

**Comment by vuhailuyen1991** [comment]
@SergeyKishenin  I tried:
*rake bower:install <package_name> --save*

But in fact they delete all my old packages and reinstall them again. 
What is the right command?

**Comment by SergeyKishenin** [comment]
Try `rake bower:install['package_name']`

**Comment by vuhailuyen1991** [comment]
done
