### ISSUE TITLE
No way to override bower_components directory

### ISSUE THREAD

**Issue by amacneil** [rharriso/bower-rails#143]
In the readme:

> By default assets are put to ./vendor/assets/bower_components directory
> But the default value can be overridden by assets_path method
> assets_path "assets/my_javascripts"

It would be nice if you did not force me to use a `bower_components` directory by appending that to the path I provide. For example, I would like to use this directory to store assets:

    vendor/assets/bower/vendor

This is because it makes a nice clean vendor namespace for sprockets which does not clash with any potentially installed gems etc: 

    //= require vendor/underscore/underscore

Is there anyway I can customize this right now? It seems that you are forcefully overriding `.bowerrc` so there is no other way to configure this.

Would you accept a PR to change the behavior?

**Comment by SergeyKishenin** [comment]
Agree. I think, this option should be configurable with default value like `/tmp/bower_components` (see discussion [here](https://github.com/rails-assets/rails-assets/issues/121#issuecomment-36356857))

Also we should give up things like:

> NOTE: Available groups are :lib and :vendor. Others are not allowed according to the Rails convention. NOTE: All the assets should be stored in /assets subdirectory so putting it under ./vendor/js directory is unavailable

Let's just give it to developers.

And YES, it would be awesome if you provide a PR!

**Comment by SergeyKishenin** [comment]
`bower_components` directory is now configurable. See #183
