### ISSUE TITLE
Can't require main file for pdfjs-dist

### ISSUE THREAD

**Issue by joallard** [rharriso/bower-rails#144]
I just installed this, 0.9.2, to use Lodash and Pdfjs. I can require Lodash, but `require pdf` will raise `Sprockets::FileNotFound` even though it is specified in the "main". Is that expected behavior?

Also tried: `asset 'pdfjs-dist', main_files: ["./build/pdf.js"]`

**Comment by SergeyKishenin** [comment]
Could you please provide directory structure for `pdfjs-dist`?

If you have like `/vendor/bower_components/pdfjs-dist/build/pdf.js` then you have to require like `//= require pdfjs-dist/build/pdf`.

We do not create aliases for main files yet just to be able to require like `require pdf`.

**Comment by joallard** [comment]
That's exactly that. Thought there was a link to the "main files".
