### ISSUE TITLE
Bower-rails don't respects main_files

### ISSUE THREAD

**Issue by phlegx** [rharriso/bower-rails#150]
Using bower-rails with this bower file configuration:

```ruby 
asset 'bootstrap-sass', '3.3.5', main_files: ['./assets/javascripts/bootstrap-sprockets.js']
```

bower rails includes only ```bootstrap.js```!

**application.js**

```ruby
//= require bootstrap-sass
```

**Comment by ain** [comment]
We're working off 4aa906f2702d611eb801066f369516d669ebeaba and it works. You're probably still on `0.9.2` which does not have this feature.
