### ISSUE TITLE
Release main_files

### ISSUE THREAD

**Issue by ain** [rharriso/bower-rails#153]
Calling for a stable release with `main_files`. 

It seems that there are also tickets coming in over this issue, e.g. #150.

We're using `main_files` in production as of 4aa906f2702d611eb801066f369516d669ebeaba so that could be a release candidate for instance.

**Comment by GeorgMeyer23** [comment]
+1

**Comment by SergeyKishenin** [comment]
Released `v0.10.0`

**Comment by ain** [comment]
Спасибо @SergeyKishenin!
