### ISSUE TITLE
How to understand main_file in Bower?

### ISSUE THREAD

**Issue by flyfy1** [rharriso/bower-rails#172]

**Comment by SergeyKishenin** [comment]
http://stackoverflow.com/a/21266210/532252

**Comment by flyfy1** [comment]
@SergeyKishenin Thanks for the fast response.. I still don't quite get it: what does it mean, if I include the files into the `main_files` option?

**Comment by SergeyKishenin** [comment]
`rake bower:clean` won't remove files which you specify with `main_files` option
