### ISSUE TITLE
`ENOENT No bower.json present` when deploying on Heroku

### ISSUE THREAD

**Issue by jfeldstein** [rharriso/bower-rails#188]
`assets:precompile` fails on Heroku with the message `ENOENT No bower.json present`. 

Specifically: 

```
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        /tmp/build_625669a6c93eff790b3ca151a29bab02/node_modules/.bin/bower install -f
remote:        bower                           ENOENT No bower.json present
```

I have heroku/nodejs and heroku/ruby buildpacks, in that order. 

My app has a `Bowerfile`.

**Comment by jfeldstein** [comment]
Interesting that on Heroku, it's not running `bower install -p`...

**Comment by jfeldstein** [comment]
I had `_use_deployment=true` and it needed to be false.

**Comment by SergeyKishenin** [comment]
Thanks for following up!

**Comment by michaeldever** [comment]
@jfeldstein How is `_use_deployment` meant to be set?
