### ISSUE TITLE
bower     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes

### ISSUE THREAD

**Issue by TechFounder** [rharriso/bower-rails#201]
I notice that I'm getting this error when i `rake bower:install`
Looking into the bower.json file that's being generated I see that first line contains: `"name": "dsl-generated dependencies",`
I believe that you have to remove the space and use something like `"name": "dl-generated-dependencies",` or `"name": "dsl-generated_dependencies",`

**Comment by SergeyKishenin** [comment]
@TechFounder I think, that we have correct name, with dashes https://github.com/rharriso/bower-rails/blob/master/lib/bower-rails/dsl.rb#L206

**Comment by TechFounder** [comment]
That's strange, why does mine not have it? I ran it several times...any ideas on how to fix?

![screen shot 2016-09-14 at 10 19 07 am](https://cloud.githubusercontent.com/assets/2199036/18515827/b697e0aa-7a64-11e6-9bce-00f7e8c39d89.png)

**Comment by SergeyKishenin** [comment]
> Could you please try to use the edge version of gem, `gem "bower-rails", github: "rharriso/bower-rails"?

**Comment by TechFounder** [comment]
Ok, that fixed it! Thanks!

**Comment by TechFounder** [comment]
BTW, when do you think we can go back to setting a version instead of using the edge version?

**Comment by SergeyKishenin** [comment]
I will make a release very soon

**Comment by TechFounder** [comment]
Great, thanks!
