### ISSUE TITLE
Don't know how to build task 'calendar:install' (see --tasks)

### ISSUE THREAD

**Issue by NeelaveniT** [rharriso/bower-rails#206]
I started to code migration to rails 4 , In the older they use calendar_date_select,
In the rails 4 ,it is not supported ,I refer the website https://github.com/bdcheung/calendar_date_select
and upgrade it . It shows as undefined method calendar_date_select

Afterwards , http://road2ruby.blogspot.in/2011/08/calendardateselect.html on this link , they specified about rake , I use it but it shows as calendar:install don't know how to bulid task .

Kindly help me,how to use calendar_date_select in rails 4 .

Thanks in advance.

**Comment by NeelaveniT** [comment]
I installed calendar_date_select and included my code also.
I able to retrieve the output of the query but it shows with is not a symbol nor a string.

In my code : 
<%= calendar_date_select "project_effective_hour[from_date]".instance_variable_get(@project_effective_hour).from_date||Date.today,popup=> 'force',:class => 'input-text'%>

Output : #<ProjectEffectiveHour id: 204, project_id: 170, effective_hours: #<BigDecimal:7f7094aae450,'0.4E1',9(18)>, from_date: "2016-02-06", to_date: "2016-05-31", created_at: "2016-02-16 18:59:11", updated_at: "2016-09-07 15:09:24", effective_hrs_for_days: 1> is not a symbol nor a string

Kindly help me to recover this.

**Comment by SergeyKishenin** [comment]
Not related to `bower-rails` gem. Please, use Stackoverflow or other Q&A services to get answer for your question

**Comment by NeelaveniT** [comment]
May I know ,why I can't get the answer for this on github ,this is related to calendar_date_select gem .

**Comment by SergeyKishenin** [comment]
Try to ask in calendar_date_select repository on Github, not bower-rails.

**Comment by NeelaveniT** [comment]
Thank you
