### ISSUE TITLE
I can't install packege for bower

### ISSUE THREAD

**Issue by Rattt** [rharriso/bower-rails#207]
I went through the instructions
 gem "bower-rails", "~> 0.11.0"
rails g bower_rails:initialize json

after run:
`bower install bootstrap`
dont'work

rake bower:install to install packages
So understand then it integrates all(bower.jon) of the packages in rails?  right?

What is the advantage over conventional bower?
bower.json

```
{
  "directory": "vendor/assets/bower_components"
}
```

config/application.rb

```
class Application < Rails::Application
  config.assets.paths << Rails.root.join('vendor', 'assets', 'bower_components')
end
```

**Comment by preetpalS** [comment]
Well one advantage is that this library integrates Bower commands within Rake. So if you use `bundle exec rake -D` you can see the various commands that this library wraps (therefore you do not have to memorize the bower commands). Additionally, if someone didn't know how to add a path to the assets path and didn't have the time to learn about it, this library would save them time. This library also allows you to configure Bower purely in Ruby as well, without using a `bower.json` file (which some people might prefer).

**Comment by SergeyKishenin** [comment]
@preetpalS thanks for explanation
