### ISSUE TITLE
@[] is not allowed as an instance variable name

### ISSUE THREAD

**Issue by NeelaveniT** [rharriso/bower-rails#208]
My code : <%= calendar_date_select "project_effective_hour[from_date]",@project_effective_hour.from_date||Date.today,:popup=> 'force',:class => 'input-text'%>

Output : `@project_effective_hour[from_date]' is not allowed as an instance variable name

Kindly help me to resolve this issue in rails 4.2.7

**Comment by SergeyKishenin** [comment]
Not related to `bower-rails` gem. Please, use Stackoverflow or other Q&A services to get answer for your question
