### ISSUE TITLE
bower:install fails with status 127

### ISSUE THREAD

**Issue by MichaelHirn** [rharriso/bower-rails#53]
Both commands bower:install and bower:update remain in a rake abortion with status 127. Don't know what that means.
`bundle exec rake bower:install`'s output:

bower.js files generated
bower install
rake aborted!
Command failed with status (127): [bower install...]

Tasks: TOP => bower:install
(See full trace by running task with --trace)

And because of that i can't precompile my assets.
Mistake in the code or at my side? And if it is on my side, what does the status tell us?

**Comment by dhgrainger** [comment]
Im still having this same problem even with gem 'bower-rails', github: '42dev/bower-rails'
