### ISSUE TITLE
Documentation should mention dependency on the "node" binary

### ISSUE THREAD

**Issue by tkhduracell** [rharriso/bower-rails#91]
The gem need the `node`-binary from nodejs-legacy in order to run. 

The error that appears when nodejs-legacy is not installed.

```
/vagrant vagrant@vagrant-ubuntu-trusty-64% rake bower:list
/usr/local/bin/bower list
rake aborted!
Command failed with status (1): [/usr/local/bin/bower list...]

Tasks: TOP => bower:list
(See full trace by running task with --trace)
```

``` sh
/vagrant vagrant@vagrant-ubuntu-trusty-64% rake bower:install
bower.js files generated
/usr/local/bin/bower install
/usr/bin/env: node: No such file or directory
rake aborted!
Command failed with status (127): [/usr/local/bin/bower install ...]

Tasks: TOP => bower:install
(See full trace by running task with --trace)
```

Solution:

``` sh
 sudo apt-get install nodejs-legacy
```

Should the documentation mention this?

**Comment by fakeplasticdroid** [comment]
Thanks for your post. I'm not sure how, but the nodejs-legacy package got uninstalled from my development machine and I was suddenly having problems with bower for no apparent reason.

**Comment by gil27** [comment]
`nodejs-legacy` :heart:

**Comment by ajahongir** [comment]
:+1:

**Comment by astrostl** [comment]
Still true in August of 2015, apparently? This saved me on a search!

**Comment by gdurelle** [comment]
:green_heart:  nodejs-legacy :heart:

**Comment by adamovichps** [comment]
+1 nodejs-legacy

**Comment by MingStar** [comment]
June/2016, still need to install nodejs-legacy to make it work
+1 Thanks!

**Comment by MingStar** [comment]
Oh, I saw that it was mentioned in the Readme. Thanks again!
